<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <RootNamespace>QuantConnect.Brokerages.Bitbank</RootNamespace>
    <AssemblyName>QuantConnect.BitbankBrokerage</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\QuantConnect.csproj" />
    <ProjectReference Include="..\Brokerages\QuantConnect.Brokerages.csproj" />
    <ProjectReference Include="..\Configuration\QuantConnect.Configuration.csproj" />
    <ProjectReference Include="..\Logging\QuantConnect.Logging.csproj" />
  </ItemGroup>
</Project>
